### ISSUE TITLE
Question: Is there a complete implementation including persistence and serialization?

### ISSUE THREAD

**Issue by jrnail23** [swlaschin/DomainModelingMadeFunctional#14]
I've been faithfully following along with the book's code examples and referring to the bundled code as well as this repo... I was disappointed to reach the chapter on persistence only to find that the persistence implementation was omitted from the final implementation of the application.

Is the full implementation available anywhere, or are there any plans to produce it?
I'd really like to see how the serialization and persistence aspects should be organized in a fully working solution.

Thanks in advance!

**Comment by swlaschin** [comment]
Thanks for commenting.  

There is an example of JSON->DTO->Domain here:
https://github.com/swlaschin/DomainModelingMadeFunctional/blob/master/src/OrderTakingEvolved/PlaceOrder.Api.fs#L134-L137

All the DTO to Domain logic is here: https://github.com/swlaschin/DomainModelingMadeFunctional/blob/master/src/OrderTakingEvolved/PlaceOrder.Dto.fs

I don't have much more than that, because this book has limited space, and so I focus on the general concepts more than a specific implementation.  

Thanks!

**Comment by swlaschin** [comment]
Closing due to age of issue. Thanks!
